config/routes.rb
Rails.application.routes.draw do
  get '/' => 'posts#index', as: 'posts'
  get '/posts/:id' => 'posts#show', as: 'post'
  get '/authors' => 'authors#index', as: 'authors'
  get '/authors/:name' => 'authors#show', as: 'author'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
  	@authors = [{name: "John Smith"}, {name: "Hugh Jass"}, {name: "Amanda Hugginkiss"}]
  end

  def show
  	name = params[:name]
  	@author = {name: name}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = [{title: "sup"}, {title: "sup again"}, {title: "hello again"}]
  end

  def show
  	@post = {title: "hi there", body: "herp derp this is my body"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/index.html.erb
<h1> This is the authors/index.html.erb page </h1>

<ul>
  <% @authors.each do |author| %>
  	<li>
  	  <%= author[:name] %>
  	</li>
  	<% end %>
</ul>

app/views/authors/show.html.erb
<h1> this is the authors/show.html.erb page </h1>

<h5> posts by <%= @author[:name] %> </h5>

app/views/layouts/_nav.html.erb
<ul>
  <li>Home</li>
  <li>About Us</li>
  <li>Contact Us</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>

<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<li>
  <%= post[:title] %>
</li>

app/views/posts/index.html.erb
<h1> This is the posts/index.html.erb page </h1>

<ul>
  <% @posts.each do |post| %>
    <%= render 'post', :post => post %>
  <% end %>
</ul>

app/views/posts/show.html.erb
<h1> This is the posts/show.html.erb page </h1>

<%= link_to 'Back to posts', posts_url %>
<h2><%= @post[:title] %></h2>
<p><%= @post[:body] %></p>